name: Deploy to ec2 on merge

on:
  push:
    branches: -main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
        uses: actions/checkout@v4
    - name: deploy to ec2
        uses: appleboy/ssh-action@master
        with: 
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Hello from github action, start deploy main to ec2"
            cd /home/ubuntu/FridgeChef
            git pull
            npm install
            npx pm2 restart all
